## 00. PyTorch Fundamentals
Video Link: https://www.youtube.com/watch?v=V_xro1bcAuA&ab_channel=freeCodeCamp.org

Online Textbook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [2]:
''' 
Start by Importing necessary libraries
'''
import torch

print(torch.__version__)

2.5.1+cpu


#### Introduction to Tensors

In [3]:
'''
Creating a Tensor

Tensors are a main building block to Machine Learning. 
Tensors are a way to represent multi-dimenstional data.

Tensors are made through torch.tensor() function
'''

scalar = torch.tensor([7])
print("What is inside scalar? ", scalar)
print("Number of Dimensions: ", scalar.ndim)

'''To get the item out of the tensor, we can use the .item() function (returns as an integer)'''
print("What is inside scalar? ", scalar.item())


What is inside scalar?  tensor([7])
Number of Dimensions:  1
What is inside scalar?  7


##### Getting Information from Tensors
1. tensor.dtype
2. tensor.shape
3. tensor.device

In [4]:
''' Creating Vectors using Tensors '''

vector = torch.tensor([1, 2, 3, 4, 5])
print("What is inside vector? ", vector) # Returns the tensor
print("Number of Dimensions: ", vector.ndim) # Returns the number of dimensions
print("What is the shape of the vector? ", vector.shape) # Returns the shape of the tensor (How many elements are in the tensor)

What is inside vector?  tensor([1, 2, 3, 4, 5])
Number of Dimensions:  1
What is the shape of the vector?  torch.Size([5])


In [5]:
''' Creating a Matrix using Tensors '''

MATRIX = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("What is inside MATRIX? ", MATRIX) # Returns the tensor
print("Number of Dimensions: ", MATRIX.ndim) # Returns the number of dimensions
print("What is the shape of the MATRIX? ", MATRIX.shape) # Returns the shape of the tensor (How many elements are in the tensor)

What is inside MATRIX?  tensor([[1, 2, 3],
        [4, 5, 6]])
Number of Dimensions:  2
What is the shape of the MATRIX?  torch.Size([2, 3])


In [6]:
''' Creating a 3D Tensor using Tensors '''

TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
print("What is inside TENSOR? \n", TENSOR) # Returns the tensor
print("Number of Dimensions: ", TENSOR.ndim) # Returns the number of dimensions
print("What is the shape of the TENSOR? ", TENSOR.shape) # Returns the shape of the tensor (How many elements are in the tensor)

What is inside TENSOR? 
 tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]])
Number of Dimensions:  3
What is the shape of the TENSOR?  torch.Size([3, 2, 3])


#### Random Tensors
Why Random Tensors? 
Random Tensors are important because many Neural Networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random data -> Look at data -> update random numbers -> look at data -> update random numbers`

In [7]:
''' Creating a random tensor '''

random_tensor = torch.rand(3, 4, 2, 5)
''' 
The way torch.rand works is that each arguement is the number of groups of the argument after it.
    So in this case, 3 is the number of groups of 4, 
    4 is the number of groups of 2, 
    and 2 is the number of groups of 5, 5 being the number of elements.
'''
print("What is inside random_tensor? \n", random_tensor) # Returns the tensor
print("Number of Dimensions: ", random_tensor.ndim) # Returns the number of dimensions

What is inside random_tensor? 
 tensor([[[[0.0731, 0.8461, 0.9785, 0.8681, 0.9573],
          [0.1986, 0.6949, 0.6739, 0.6008, 0.3476]],

         [[0.6067, 0.2448, 0.5032, 0.7642, 0.2158],
          [0.3109, 0.9697, 0.8953, 0.7569, 0.1738]],

         [[0.5375, 0.8682, 0.2896, 0.8490, 0.8695],
          [0.8984, 0.2253, 0.3847, 0.7422, 0.5375]],

         [[0.7731, 0.5716, 0.0884, 0.5693, 0.5619],
          [0.7087, 0.7920, 0.2064, 0.9696, 0.7956]]],


        [[[0.4872, 0.1540, 0.6770, 0.5053, 0.9958],
          [0.6720, 0.6533, 0.4519, 0.3049, 0.6528]],

         [[0.3858, 0.4987, 0.6877, 0.2976, 0.2911],
          [0.6202, 0.6771, 0.5067, 0.5312, 0.0031]],

         [[0.2646, 0.0426, 0.0435, 0.9423, 0.1815],
          [0.2037, 0.1087, 0.2522, 0.5818, 0.7901]],

         [[0.5241, 0.2131, 0.5566, 0.8620, 0.6767],
          [0.5339, 0.0539, 0.9440, 0.7605, 0.3388]]],


        [[[0.1196, 0.1989, 0.5892, 0.7948, 0.3393],
          [0.9937, 0.6221, 0.4715, 0.8695, 0.8588]],

         [

In [8]:
''' 
Create a random tensor with a similar shape to an image tensor 

When we convert images into tensors, we usually have a shape of (height, width, color_channels(R, G, B))
'''

random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

#### Zeros and Ones Tensor

In [9]:
''' Create a tensor of all zeros '''
zeros = torch.zeros(size=(3,4))
print("What is inside zeros? \n", zeros) # Returns the tensor

ones = torch.ones(size=(3,4))
print("\nWhat is inside ones? \n", ones) # Returns the tensor

What is inside zeros? 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

What is inside ones? 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


#### Creating a range of tensors and tensors-like

In [10]:
tensor_range = torch.arange(start=1, end=11, step=1)
tensor_range

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
tensor_like =torch.zeros_like(tensor_range)
tensor_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Tensor Datatypes

In [12]:
float_32_tensor = torch.tensor([1.0, 2.0, 3.0], 
                               dtype=None, # What datatype is the tensor 
                               device=None, # What device is the tensor on
                               requires_grad=False # Do we need to keep track of the data's gradient?
                               )
float_32_tensor

tensor([1., 2., 3.])

In [13]:
float_16_tensor = float_32_tensor.type(dtype=torch.float16),
float_16_tensor

(tensor([1., 2., 3.], dtype=torch.float16),)

#### Manipulating Tensors (Tensor Operations)
Tensor Operations include:

-> Addition

-> Subtraction

-> Multiplication (element-wise)

-> Division

-> Matrix Multiplication

In [14]:
tensor = torch.tensor([1, 2, 3])
print(tensor + 10)
print(tensor - 10)
print(tensor * 10)
print(tensor / 10)
print(tensor ** 2)
    
''' Dot Product '''
print("Dot Product")
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])

print(torch.dot(tensor1, tensor2))

''' Matrix Multiplication '''
print("\nMatrix Multiplication\n")
matrix1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
matrix2 = torch.tensor([[7, 8], [9, 10], [11, 12]])

print(torch.matmul(matrix1, matrix2))

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])
tensor([1, 4, 9])
Dot Product
tensor(32)

Matrix Multiplication

tensor([[ 58,  64],
        [139, 154]])


#### Reshaping, Stacking, Squeezing, and Unsqueezing Tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of eachother (vstack) or side by side (hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - adds a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [15]:
x = torch.arange(1, 16)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]),
 torch.Size([15]))

In [16]:
''' Add an extra dimension to the tensor '''

x_reshaped = x.reshape(5, 3) # 5 x 3 = 15 (The number of elements in the tensor)
x_reshaped, x_reshaped.shape

(tensor([[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12],
         [13, 14, 15]]),
 torch.Size([5, 3]))

In [17]:
''' Change the view '''
z = x.view(5, 3)
z, z.shape

(tensor([[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12],
         [13, 14, 15]]),
 torch.Size([5, 3]))

In [18]:
''' Changing the view changes the original tensor '''
z[:, 0] = 1 # All the rows in the first column will be 0
''' Notice how the first column of the original tensor has changed '''
z, x

(tensor([[ 1,  2,  3],
         [ 1,  5,  6],
         [ 1,  8,  9],
         [ 1, 11, 12],
         [ 1, 14, 15]]),
 tensor([ 1,  2,  3,  1,  5,  6,  1,  8,  9,  1, 11, 12,  1, 14, 15]))

In [19]:
''' Stack tensors on top of each other '''
stacked = torch.stack([x, x, x, x, x])
print(stacked)

print('\n')
print('\n')

''' Stack tensors side by side '''
stacked_side_by_side = torch.hstack([x, x, x, x, x])
print(stacked_side_by_side)


tensor([[ 1,  2,  3,  1,  5,  6,  1,  8,  9,  1, 11, 12,  1, 14, 15],
        [ 1,  2,  3,  1,  5,  6,  1,  8,  9,  1, 11, 12,  1, 14, 15],
        [ 1,  2,  3,  1,  5,  6,  1,  8,  9,  1, 11, 12,  1, 14, 15],
        [ 1,  2,  3,  1,  5,  6,  1,  8,  9,  1, 11, 12,  1, 14, 15],
        [ 1,  2,  3,  1,  5,  6,  1,  8,  9,  1, 11, 12,  1, 14, 15]])




tensor([ 1,  2,  3,  1,  5,  6,  1,  8,  9,  1, 11, 12,  1, 14, 15,  1,  2,  3,
         1,  5,  6,  1,  8,  9,  1, 11, 12,  1, 14, 15,  1,  2,  3,  1,  5,  6,
         1,  8,  9,  1, 11, 12,  1, 14, 15,  1,  2,  3,  1,  5,  6,  1,  8,  9,
         1, 11, 12,  1, 14, 15,  1,  2,  3,  1,  5,  6,  1,  8,  9,  1, 11, 12,
         1, 14, 15])


In [20]:
''' Lets see squeeze and unsqueeze in action '''
print(x, "\n")
x_unsqueezed = x.unsqueeze(dim=1)

print(x_unsqueezed, "\n")

tensor([ 1,  2,  3,  1,  5,  6,  1,  8,  9,  1, 11, 12,  1, 14, 15]) 

tensor([[ 1],
        [ 2],
        [ 3],
        [ 1],
        [ 5],
        [ 6],
        [ 1],
        [ 8],
        [ 9],
        [ 1],
        [11],
        [12],
        [ 1],
        [14],
        [15]]) 



In [31]:
''' Lets see permute in action '''
x_original = torch.rand(size=(224, 315, 3)) # [height, width, color_channels]
x_permuted = x_original.permute(1, 2 ,0) # shifts axis 2->0, 0->1, 1->2
print("Previous Shape", x_original.shape)
print("\nNew Shape", x_permuted.shape)

Previous Shape torch.Size([224, 315, 3])

New Shape torch.Size([315, 3, 224])


#### PyTorch and NumPy

* `torch.from_numpy(ndarray)`

In [33]:
import numpy as np

array = np.arange(1.5, 10.5, 1.5)
tensor = torch.from_numpy(array)
array, tensor

(array([1.5, 3. , 4.5, 6. , 7.5, 9. ]),
 tensor([1.5000, 3.0000, 4.5000, 6.0000, 7.5000, 9.0000], dtype=torch.float64))