## 00. PyTorch Fundamentals
Video Link: https://www.youtube.com/watch?v=V_xro1bcAuA&ab_channel=freeCodeCamp.org

Online Textbook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [2]:
''' 
Start by Importing necessary libraries
'''

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.5.1+cpu


#### Introduction to Tensors

In [5]:
'''
Creating a Tensor

Tensors are a main building block to Machine Learning. 
Tensors are a way to represent multi-dimenstional data.

Tensors are made through torch.tensor() function
'''

scalar = torch.tensor([7])
print("What is inside scalar? ", scalar)
print("Number of Dimensions: ", scalar.ndim)

'''To get the item out of the tensor, we can use the .item() function (returns as an integer)'''
print("What is inside scalar? ", scalar.item())


What is inside scalar?  tensor([7])
Number of Dimensions:  1
What is inside scalar?  7


In [11]:
''' Creating Vectors using Tensors '''

vector = torch.tensor([1, 2, 3, 4, 5])
print("What is inside vector? ", vector) # Returns the tensor
print("Number of Dimensions: ", vector.ndim) # Returns the number of dimensions
print("What is the shape of the vector? ", vector.shape) # Returns the shape of the tensor (How many elements are in the tensor)

What is inside vector?  tensor([1, 2, 3, 4, 5])
Number of Dimensions:  1
What is the shape of the vector?  torch.Size([5])


In [16]:
''' Creating a Matrix using Tensors '''

MATRIX = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("What is inside MATRIX? ", MATRIX) # Returns the tensor
print("Number of Dimensions: ", MATRIX.ndim) # Returns the number of dimensions
print("What is the shape of the MATRIX? ", MATRIX.shape) # Returns the shape of the tensor (How many elements are in the tensor)

What is inside MATRIX?  tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Number of Dimensions:  2
What is the shape of the MATRIX?  torch.Size([3, 3])


In [22]:
''' Creating a 3D Tensor using Tensors '''

TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
print("What is inside TENSOR? \n", TENSOR) # Returns the tensor
print("Number of Dimensions: ", TENSOR.ndim) # Returns the number of dimensions
print("What is the shape of the TENSOR? ", TENSOR.shape) # Returns the shape of the tensor (How many elements are in the tensor)

What is inside TENSOR? 
 tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]])
Number of Dimensions:  3
What is the shape of the TENSOR?  torch.Size([3, 2, 3])
tensor(6)


#### Random Tensors
Why Random Tensors? 
Random Tensors are important because many Neural Networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random data -> Look at data -> update random numbers -> look at data -> update random numbers`

In [29]:
''' Creating a random tensor '''

random_tensor = torch.rand(3, 4, 2, 5)
''' 
The way torch.rand works is that each arguement is the number of groups of the argument after it.
    So in this case, 3 is the number of groups of 4, 
    4 is the number of groups of 2, 
    and 2 is the number of groups of 5, 5 being the number of elements.
'''
print("What is inside random_tensor? \n", random_tensor) # Returns the tensor
print("Number of Dimensions: ", random_tensor.ndim) # Returns the number of dimensions

What is inside random_tensor? 
 tensor([[[[0.6835, 0.4848, 0.2471, 0.9906, 0.0326],
          [0.6519, 0.4964, 0.8066, 0.0305, 0.4377]],

         [[0.2447, 0.7272, 0.4018, 0.8579, 0.6073],
          [0.1494, 0.2682, 0.9953, 0.0440, 0.6250]],

         [[0.0180, 0.6019, 0.0125, 0.1896, 0.1829],
          [0.8633, 0.6210, 0.0146, 0.3241, 0.2637]],

         [[0.8002, 0.3385, 0.7874, 0.1664, 0.1861],
          [0.7714, 0.4394, 0.7087, 0.7424, 0.7406]]],


        [[[0.5573, 0.4174, 0.7651, 0.8846, 0.9314],
          [0.7460, 0.7785, 0.6648, 0.3425, 0.7448]],

         [[0.6435, 0.8127, 0.8156, 0.9480, 0.5174],
          [0.3231, 0.2072, 0.1457, 0.3520, 0.8483]],

         [[0.9192, 0.1440, 0.1936, 0.5818, 0.6253],
          [0.4550, 0.8594, 0.8696, 0.0143, 0.9295]],

         [[0.0498, 0.6416, 0.7203, 0.4712, 0.8587],
          [0.8494, 0.0724, 0.5589, 0.9542, 0.3590]]],


        [[[0.9322, 0.8085, 0.3665, 0.9481, 0.4668],
          [0.1497, 0.8155, 0.4098, 0.8610, 0.5481]],

         [

In [30]:
''' 
Create a random tensor with a similar shape to an image tensor 

When we convert images into tensors, we usually have a shape of (height, width, color_channels(R, G, B))
'''

random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

#### Zeros and Ones Tensor

In [33]:
''' Create a tensor of all zeros '''
zeros = torch.zeros(size=(3,4))
print("What is inside zeros? \n", zeros) # Returns the tensor

ones = torch.ones(size=(3,4))
print("\nWhat is inside ones? \n", ones) # Returns the tensor

What is inside zeros? 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

What is inside ones? 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


#### Creating a range of tensors and tensors-like

In [40]:
tensor_range = torch.arange(start=1, end=11, step=1)
tensor_range

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
tensor_like =torch.zeros_like(tensor_range)
tensor_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Tensor Datatypes

In [45]:
float_32_tensor = torch.tensor([1.0, 2.0, 3.0], 
                               dtype=None, # What datatype is the tensor 
                               device="cpu", # What device is the tensor on
                               requires_grad=False # Do we need to keep track of the data's gradient?
                               )
float_32_tensor

tensor([1., 2., 3.])

In [47]:
float_16_tensor = float_32_tensor.type(dtype=torch.float16),
float_16_tensor

(tensor([1., 2., 3.], dtype=torch.float16),)